.base:
  timeout: 5 minutes
  before_script:
    - apt-get update || true
    - apt-get install -y unzip
    - apt-get install -y git
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer update --prefer-dist

.php80:
  image: php:8.0
  extends: .base

stages:
  - quality

# PHPStan

phpstan80:
  extends: .php80
  stage: quality
  except:
    - master
  script:
    - ./vendor/bin/phpstan analyse -c phpstan.neon

# PHP code sniffer

phpcs80:
  extends: .php80
  stage: quality
  except:
    - master
  script:
    - ./vendor/bin/phpcs --standard=./phpcs.xml

# PHPUnit

phpunit80:
  extends: .php80
  stage: quality
  except:
    - master
  script:
    - ./vendor/bin/phpunit -c phpunit.xml --do-not-cache-result

# Psalm

psalm80:
  extends: .php80
  stage: quality
  except:
    - master
  script:
    - ./vendor/bin/psalm
